---
image: localhost:5000/ansible/test-runner:latest

stages:
    - build:

ansible_build:
    stage: build
    script:
        - cd tests
        - ansible-playbook test.yml --syntax-check
        - ansible-playbook test.yml
        - py.test -v test.py --hosts='docker://localhost'
    after_script:
        - docker rm -f localhost
