---
image:
    name: williamyeh/ansible:centos7
<<<<<<< HEAD
    entrypoint: ["/lib/systemd/systemd","&&"]
=======
    entrypoint: ["/sbin/init"]
>>>>>>> 7e819e41324b9d816065881f90e12a82fdddcbd2

stages:
    - lint:
    - build:

before_script:
    #    - yum -y install gcc gcc-c++ kernel-devel
    #    - yum -y install python-devel
    #    - pip install testinfra
    - cd tests

syntax_check:
    stage: lint
    script:
        - ansible-playbook test.yml --syntax-check

ansible_build:
    stage: build
    script:
        - ansible-playbook test.yml
          #        - py.test -v test.py
