---
- name: restart nginx service
  service:
    name: nginx
    state: restarted
  tags: nginx

- name: restart keepalived service
  service:
    name: keepalived
    state: restarted
  when: test_skip is undefined
  tags: nginx

- name: restart consul-template service
  service:
    name: consul-template
    state: restarted
  when: test_skip is undefined
  tags: nginx
